"""FigTreeKit: Programmatic styling of phylogenetic trees for FigTree visualization.

>>> from figtreekit import FigTreeStyler, LayoutType
>>> styler = FigTreeStyler("input.tre")
>>> styler.set_layout(LayoutType.POLAR)
>>> styler.export("styled.nex")
>>> styler.render("tree.png")  # Requires FigTree JAR (figtreekit setup-figtree)
"""

# Copyright (C) 2024-2026 Zeng Zichao
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import os
from pathlib import Path

__author__ = "Zeng Zichao"
__email__ = "zengzichao@sjtu.edu.cn"
__license__ = "GPL-2.0-or-later"

# ── Version discovery (setuptools_scm with fallback) ───────────────────
# Try _version.py (generated by setuptools_scm at build time), then
# runtime setuptools_scm discovery, then static fallback.
__version__ = "1.0.0"
__version_date__ = ""
__git_hash__ = ""

try:
    from ._version import __version__, __version_date__, __git_hash__  # type: ignore
except ImportError:
    # _version.py is generated at build time by setuptools_scm. When running
    # from a source checkout that lacks it, fall back to live SCM discovery,
    # and finally to the static version defined above. Failures here are
    # non-fatal: we keep the static fallback rather than crashing.
    import logging
    logger = logging.getLogger(__name__)
    try:
        from setuptools_scm import get_version
        _scm_version = get_version(root="..", relative_to=__file__)
        if _scm_version:
            __version__ = _scm_version
    except Exception as exc:  # pragma: no cover - depends on SCM availability
        logger.debug(
            "setuptools_scm version discovery unavailable; using static "
            "version %s: %s",
            __version__,
            exc,
        )

from .annotations import CladeCollapse, NodeAnnotation
from .enums import FontStyle, LayoutType, OrderType, RootingType, TransformType
from .exceptions import (
    CompatibilityWarning,
    ExportError,
    MonophylyError,
    ParseError,
    PhyloFormatError,
    FigTreeKitError,
    RenderError,
    TaxonomyConflictError,
    ValidationError,
)
from .styler import FigTreeSettings, FigTreeStyler
from .validators import TreeValidator
from .validators import (
    validate_input_file, TREE_EXTENSIONS, SEQUENCE_EXTENSIONS,
    deep_validate_newick, deep_validate_fasta, deep_validate_fastq,
    summarize_nexus_trees,
    scan_for_anomalous_content,
    detect_taxonomy_circular_deps,
    cross_validate_tree_sequence, read_text_with_fallback,
    extract_sequence_ids,
)
from ._parser import extract_taxa_from_newick
from .taxonomy import (
    TaxonomyMapper, MonophylyAnalyzer, SPECIAL_IDENTIFIERS,
    parse_taxonomy_auto, detect_taxonomy_format,
    get_rank_prefixes, set_rank_prefixes, extend_rank_prefixes,
)
from ._renderer import find_figtree_jar, render_with_figtree, render_multiple
from ._figtree_setup import setup_figtree, check_figtree, print_setup_status
from ._cli import apply_cli_args


# ── Library-mode API (§8.2) ─────────────────────────────────────────────
# Thin wrappers with standardized signatures for third-party workflow
# integration (Snakemake/Nextflow).  These use plain Python types and
# the standardized exception hierarchy.

def parse_taxonomy(label: str, mode: str = "reverse") -> dict:
    """Parse a taxonomy label into a rank→value dict.

    Args:
        label: Taxonomy string (embedded format A or table format B).
        mode: Parsing mode for embedded format (``reverse``, ``greedy``,
            ``segment``). Default ``reverse``.

    Returns:
        Dict mapping rank names (``domain``, ``phylum``, ...) to values.
        Empty dict if no taxonomy detected.

    Raises:
        PhyloFormatError: If the label contains malformed taxonomy.
    """
    return parse_taxonomy_auto(label, mode=mode)


def is_monophyletic(tree, taxon_label: str, rooted: bool = True) -> bool:
    """Check if a taxonomic group forms a monophyletic clade.

    Args:
        tree: Path to tree file, Newick string, or ``FigTreeStyler``
            instance.
        taxon_label: Taxonomic label to test (e.g. ``"Cyanobacteriota"``).
        rooted: If ``True``, treat the tree as rooted (default).

    Returns:
        ``True`` if the group is monophyletic, ``False`` otherwise.

    Raises:
        MonophylyError: If the taxon is not found or tree is invalid.
    """
    if isinstance(tree, FigTreeStyler):
        styler = tree
    elif isinstance(tree, str):
        if os.path.exists(tree):
            # A real file path always wins over content sniffing, so paths
            # that legitimately contain '(' (e.g. './my(tree).tre') are not
            # misclassified as inline Newick content.
            styler = FigTreeStyler().load_tree(tree)
        else:
            # Inline Newick/Nexus content (contains parentheses or newlines).
            styler = FigTreeStyler().load_content(tree)
    else:
        raise TypeError(
            "expected a tree path, Newick string, or Bio.Phylo tree"
        )
    # Monophyly is decided by a unified MRCA-set comparison
    # (mrca_set == target_set) inside check_monophyly_by_group, which uses
    # Bio.Phylo's common_ancestor — no separate path/inline logic here.
    result = styler.check_monophyly_by_group(taxon_label)
    taxa = result.get("resolved_taxa", [])
    if not taxa:
        raise MonophylyError(f"Taxon '{taxon_label}' not found in tree")
    return result.get("is_monophyletic", False)


def load_tree(path, validate: bool = True):
    """Load a phylogenetic tree file.

    Args:
        path: Path to a Newick or Nexus tree file.
        validate: If ``True`` (default), perform deep validation: format
            detection, structural checks, and (for Newick) branch-length /
            balance validation.  When ``False``, only negative-branch-length
            checking (``strict``) is applied by the parser.

    Returns:
        ``FigTreeStyler`` instance with the tree loaded.

    Raises:
        PhyloFormatError: If the file format is invalid.
        ValidationError: If validation fails.
    """
    p = Path(path)
    if not p.exists():
        raise PhyloFormatError(f"Tree file not found: {path}")

    if validate:
        vresult = validate_input_file(str(p))
        if not vresult["valid"]:
            raise ValidationError(
                "Tree file failed validation:\n" + "\n".join(vresult["errors"])
            )
        fmt = vresult["format"]
        if fmt == "newick":
            with open(p, 'r', encoding='utf-8', errors='replace') as f:
                content = f.read()
            dv = deep_validate_newick(content, label=p.name)
            if dv["errors"]:
                raise ValidationError(
                    "Tree failed deep validation:\n" + "\n".join(dv["errors"])
                )
        elif fmt == "nexus":
            summaries = summarize_nexus_trees(str(p))
            for ts in summaries:
                if ts.get("has_negative_bl"):
                    raise ValidationError(
                        f"Tree '{ts.get('name')}' contains negative branch "
                        f"length(s), which FigTree cannot render."
                    )
        elif fmt not in ("newick", "nexus"):
            # A non-tree format slipped past extension/content detection.
            raise ValidationError(
                f"File '{path}' is not a supported tree format "
                f"(detected '{fmt}'; expected Newick or Nexus)."
            )

    styler = FigTreeStyler(strict=validate)
    return styler.load_tree(str(p))


def cross_validate(tree_path, seq_path, strict: bool = True) -> dict:
    """Cross-validate tree tip labels against sequence IDs.

    Args:
        tree_path: Path to the tree file.
        seq_path: Path to the sequence file (FASTA/FASTQ).
        strict: If ``True`` (default), any mismatch is an error.

    Returns:
        Dict with keys: ``valid`` (bool), ``matched`` (int),
        ``tree_only`` (list), ``seq_only`` (list), ``errors`` (list).

    Raises:
        PhyloFormatError: If the files cannot be parsed.
    """
    # Extract tree tip labels (handles Newick + Nexus, including translate
    # blocks).  The previous implementation passed the *file paths* straight
    # into cross_validate_tree_sequence, which expects *label lists* — so the
    # comparison never actually ran.
    try:
        styler = FigTreeStyler(str(tree_path))
    except (ParseError, FileNotFoundError, OSError) as e:
        raise PhyloFormatError(f"Cannot parse tree file '{tree_path}': {e}")
    tree_content = styler.get_tree_content()
    if not tree_content:
        raise PhyloFormatError(f"Could not extract a tree from: {tree_path}")
    taxa = extract_taxa_from_newick(tree_content)
    if getattr(styler, "_translate_block", None):
        try:
            translate_map = styler._parse_translate_block()
        except Exception:
            translate_map = {}
        id_to_name = {tid: name for name, tid in translate_map.items()}
        taxa = [id_to_name.get(t, t) for t in taxa]

    # Extract sequence IDs lazily (memory-friendly for large sequence files).
    try:
        seq_ids = extract_sequence_ids(seq_path)
    except (OSError, ValueError) as e:
        raise PhyloFormatError(f"Cannot read sequence file '{seq_path}': {e}")

    result = cross_validate_tree_sequence(taxa, seq_ids)
    if strict and result.get("errors"):
        raise PhyloFormatError(
            "Cross-validation failed:\n" + "\n".join(result["errors"])
        )
    return {
        "valid": not result.get("errors"),
        "matched": result.get("matched", 0),
        "tree_only": result.get("only_in_tree", []),
        "seq_only": result.get("only_in_sequences", []),
        "errors": result.get("errors", []),
    }

__all__ = [
    # Core
    "FigTreeStyler",
    "FigTreeSettings",
    # Enums
    "LayoutType",
    "TransformType",
    "RootingType",
    "OrderType",
    "FontStyle",
    # Exceptions
    "FigTreeKitError",
    "ParseError",
    "ValidationError",
    "ExportError",
    "CompatibilityWarning",
    "PhyloFormatError",
    "RenderError",
    "TaxonomyConflictError",
    "MonophylyError",
    # Data
    "CladeCollapse",
    "NodeAnnotation",
    "TreeValidator",
    "validate_input_file",
    "deep_validate_newick",
    "deep_validate_fasta",
    "deep_validate_fastq",
    "summarize_nexus_trees",
    "scan_for_anomalous_content",
    "detect_taxonomy_circular_deps",
    "cross_validate_tree_sequence",
    "read_text_with_fallback",
    "TREE_EXTENSIONS",
    "SEQUENCE_EXTENSIONS",
    # Taxonomy
    "TaxonomyMapper",
    "MonophylyAnalyzer",
    "SPECIAL_IDENTIFIERS",
    "parse_taxonomy_auto",
    "detect_taxonomy_format",
    "get_rank_prefixes",
    "set_rank_prefixes",
    "extend_rank_prefixes",
    # Rendering
    "find_figtree_jar",
    "render_with_figtree",
    "render_multiple",
    # FigTree Setup
    "setup_figtree",
    "check_figtree",
    "print_setup_status",
    "apply_cli_args",
    # Library-mode API (§8.2)
    "parse_taxonomy",
    "is_monophyletic",
    "load_tree",
    "cross_validate",
]
