"""
Quick visual test — run after installation to verify rendering works.

Usage:
    python examples/02_visual_test.py

Output directory:
    examples/output/

Produces 3 PNG + 3 PDF files from fully synthetic trees with anonymous
taxon codes.  The trees are generated by a neutral Yule process and are
intended only for visual regression testing.
"""

import random
from pathlib import Path

from figtreekit import FigTreeStyler, LayoutType, FontStyle

OUT = Path(__file__).parent / "output"
OUT.mkdir(exist_ok=True)

random.seed(42)


def _generate_codes(prefix: str, count: int) -> list:
    width = max(3, len(str(count)))
    return [f"{prefix}{i:0{width}d}" for i in range(1, count + 1)]


def generate_random_tree(taxa: list, branch_scale: float = 0.01) -> str:
    """Generate a random ultrametric Newick tree using a Yule process."""
    nodes = list(taxa)
    while len(nodes) > 1:
        i, j = random.sample(range(len(nodes)), 2)
        bl_a = round(random.expovariate(1.0 / branch_scale), 6)
        bl_b = round(random.expovariate(1.0 / branch_scale), 6)
        parent = f"({nodes[i]}:{bl_a},{nodes[j]}:{bl_b})"
        nodes = [n for k, n in enumerate(nodes) if k not in (i, j)] + [parent]
    return nodes[0] + ";"


def render(styler, name, width=3000, height=4500):
    """Export Nexus + render PNG/PDF."""
    nex = OUT / f"{name}.nex"
    styler.export(str(nex))

    png = OUT / f"{name}.png"
    pdf = OUT / f"{name}.pdf"
    try:
        styler.render(str(png), format="PNG", width=width, height=height)
        styler.render(str(pdf), format="PDF", width=width, height=height)
        print(f"  {png.name} ({png.stat().st_size // 1024} KB)")
        print(f"  {pdf.name} ({pdf.stat().st_size // 1024} KB)")
    except Exception as e:
        print(f"  Rendering failed (FigTree JAR not found?): {e}")
        print(f"  Nexus file saved: {nex.name}")


# ══════════════════════════════════════════════════════════
print("=== FigTreeKit Visual Test ===\n")

# ── 1. Small rectangular tree with clade highlighting ─────
print("1. Small tree (20 taxa, rectilinear layout)")

taxa_20 = _generate_codes("S", 20)
tree_20 = generate_random_tree(taxa_20, branch_scale=0.02)

s1 = FigTreeStyler().load_content(tree_20)
s1.set_layout(LayoutType.RECTILINEAR, expansion=100)
s1.set_tip_labels(is_shown=True, font_name="Helvetica", font_size=20, font_style=FontStyle.BOLD)
s1.set_appearance(branch_line_width=3.0, foreground_color="#2C3E50", background_color="#FAFAFA")
s1.set_scale_bar(is_shown=True, font_size=14)

# Highlight arbitrary clades for visual testing
s1.highlight_clade(taxa_20[:7], color="#FFCDD2", width=10, offset=0.5)
s1.set_clade_color_all(taxa_20[:7], color="#C62828")

s1.highlight_clade(taxa_20[7:14], color="#BBDEFB", width=10, offset=0.5)
s1.set_clade_color_all(taxa_20[7:14], color="#1565C0")

s1.set_clade_font([taxa_20[0]], "Helvetica", FontStyle.BOLD, 24)

render(s1, "small_tree", 2400, 3200)

# ── 2. Large rectangular tree with multiple clade colors ──
print("\n2. Large tree (50 taxa, rectilinear layout)")

taxa_50 = _generate_codes("L", 50)
tree_50 = generate_random_tree(taxa_50, branch_scale=0.01)

s2 = FigTreeStyler().load_content(tree_50)
s2.set_layout(LayoutType.RECTILINEAR, expansion=80)
s2.set_tip_labels(is_shown=True, font_name="Helvetica", font_size=14, font_style=FontStyle.BOLD)
s2.set_appearance(branch_line_width=2.5, foreground_color="#1A1A2E", background_color="#FAFAFA")
s2.set_scale_bar(is_shown=True, font_size=12)

groups = [
    (taxa_50[:10], "#C62828", "#FFCDD2"),
    (taxa_50[10:20], "#1565C0", "#BBDEFB"),
    (taxa_50[20:30], "#E65100", "#FFE0B2"),
    (taxa_50[30:40], "#2E7D32", "#C8E6C9"),
    (taxa_50[40:], "#6A1B9A", "#E1BEE7"),
]
for names, branch_color, hl_color in groups:
    s2.set_clade_color_all(names, color=branch_color)
    s2.highlight_clade(names, color=hl_color, width=12, offset=0.5)

s2.set_clade_font([taxa_50[0]], "Helvetica", FontStyle.BOLD, 18)

render(s2, "large_tree", 3000, 4500)

# ── 3. Polar bacterial-style tree with bootstrap colors ───
print("\n3. Polar tree (10 taxa, circular layout)")

taxa_10 = _generate_codes("P", 10)
tree_10 = generate_random_tree(taxa_10, branch_scale=0.03)

s3 = FigTreeStyler().load_content(tree_10)
s3.set_layout(LayoutType.POLAR)
s3.set_polar_layout(angular_range=360, root_angle=90, align_tip_labels=True)
s3.set_tip_labels(is_shown=True, font_name="Helvetica", font_size=18, font_style=FontStyle.BOLD)
s3.set_appearance(branch_line_width=3.0, foreground_color="#37474F", background_color="#ECEFF1")
s3.set_scale_bar(is_shown=True, font_size=12)

s3.set_clade_color_all(taxa_10[:3], color="#D32F2F")
s3.highlight_clade(taxa_10[:3], color="#FFCDD2", width=10, offset=0.5)

s3.set_clade_color_all(taxa_10[3:6], color="#1976D2")
s3.highlight_clade(taxa_10[3:6], color="#BBDEFB", width=10, offset=0.5)

s3.set_clade_color_all(taxa_10[6:], color="#388E3C")
s3.highlight_clade(taxa_10[6:], color="#C8E6C9", width=10, offset=0.5)

render(s3, "polar_tree", 2400, 2400)

print("\nDone! Open the PNG files to view the results.")
